<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 30.10.17
 * Time: 9:16
 */
?>

<div class="page-title-wrapper testimonials__header">
    <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
        <span class="base" data-ui-id="page-title-wrapper">
            <strong>Testimomials</strong>
        </span>
    </h1>
    <button id="open_modal_tst">SUBMIT YOUR TESTIMONIAL</button>
</div>
